config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:create, :new, :show] do
    get :activate, on: :collection
  end
  resource :session, only: [:create, :new, :destroy]

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, except: [:index, :new] do
    resources :tracks, only: [:new]
  end

  resources :tracks, except: [:index, :new] do
    resources :notes, only: [:create]
  end

  resources :notes, only: [:destroy]

end

app/models/note.rb
class Note < ApplicationRecord
  validates :user_id, :track_id, :text, presence: true

  belongs_to :user
  belongs_to :track
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def create
    @note = Note.new(note_params)
    @note.user_id = current_user.id
    @note.track_id = params[:track_id]
    if @note.save
    else
      flash[:errors] = @note.errors.full_messages
    end

    redirect_to track_url(params[:track_id])
  end

  def destroy
    @note = Note.find(params[:id])
    if @note.user == current_user
      @note.destroy
      redirect_to track_url(@note.track)
    else
      render status: :forbidden, text: "hey you can't do that"
    end
  end

  private

  def note_params
    params.require(:note).permit(:user_id, :track_id, :text)
  end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<form action="<%= track_notes_url(track) %>" method="POST">
  <%= auth_token %>
  <label>New Note:
    <br>
  <textarea name="note[text]" rows="8" cols="80">

  </textarea></label>

  <br><br>

  <input type="submit">

</form>

app/views/notes/_note.html.erb
<ul>
  <% @track.notes.reverse_each do |note| %>
  <li>
    <%= note.text %>
    <br>
    -written by <%= note.user.email %>
    <% text = note.user == current_user ? "Delete Note" : "Delete Note (you can't lol)" %>
      <%= button_to text, note_url(note), method: :delete  %>
   </li>

   <br>
  <% end %>
</ul>