config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:create, :new, :show] do
    get :activate, on: :collection
  end
  resource :session, only: [:create, :new, :destroy]

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, except: [:index, :new] do
    resources :tracks, only: [:new]
  end

  resources :tracks, except: [:index, :new] do
    resources :notes, only: [:create]
  end

  resources :notes, only: [:destroy]

end

app/models/track.rb
class Track < ApplicationRecord
  TRACK_TYPES = %w(bonus regular)

  validates :title, presence: true
  validates :album_id, presence: true
  validates :track_type, inclusion: TRACK_TYPES

  belongs_to :album
  has_one :band,
    through: :album,
    source: :band
  has_many :notes, dependent: :destroy
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :ensure_logged_in
  def new
    @album = Album.find(params[:album_id])
    @track = Track.new
    render :new
  end

  def create
    @track = Track.new(track_params)
    if @track.save
      redirect_to track_url(@track)
    else
      flash[:errors] = @track.errors.full_messages
      redirect_to new_album_track_url(@track.album)
    end
  end

  def edit
    @track = Track.find(params[:id])
    render :edit
  end

  def update
    @track = Track.find(params[:id])
    if @track.update_attributes(track_params)
      redirect_to track_url(@track)
    else
      flash[:errors] = @track.errors.full_messages
      redirect_to edit_track_url(@track)
    end
  end

  def show
    @track = Track.find(params[:id])
    render :show
  end

  def destroy
    @track = Track.find(params[:id])
    @track.destroy
    redirect_to album_url(@track.album)
  end

  private

  def track_params
    params.require(:track).permit(:title, :album_id, :track_type, :lyrics)
  end

end

app/helpers/tracks_helper.rb
module TracksHelper
  include ERB::Util

  def ugly_lyrics(lyrics)
    lines = lyrics.split("\n")
    lines.map do |line|
      ("&#9835 " + h(line)).html_safe
    end
  end
end

app/views/tracks/_form.html.erb
<% action = (track.persisted? ? :edit : :new) %>

<form action="<%=(action==:edit ? track_url(track) : tracks_url)%>" method="POST">
  <% if action == :edit %>
    <input type="hidden" name="_method" value="PATCH">
  <% end %>
  <%= auth_token %>

  <label for="track_name">Track name: </label>
  <input  id = "track_name"
          type="text" name="track[title]"
          placeholder = "Track name"
          value="<%=track.title%>">

  <br>

  <label for="track_album_id">Album</label>
  <select id="track_album_id" name="track[album_id]">
    <% Album.all.each do |album| %>
      <option value="<%= album.id %>"
              <%= 'selected' if album.title == current_album.title %>>
              <%= album.band.name%>: <%= album.title %>
      </option>
    <% end %>
  </select>

  <br>

  <label>Track Type:
    Regular <input  type="radio"
                    name="track[track_type]"
                    value="regular"
                    <%= 'checked' if track.track_type == 'regular' %>>
    Bonus <input  type="radio"
                  name="track[track_type]"
                  value="bonus"
                  <%= 'checked' if track.track_type == 'bonus' %>>
  </label>

  <br>

  <label for="track_lyrics">Lyrics: </label>
  <br>
  <textarea id="track_lyrics" name="track[lyrics]" rows="8" cols="60"><%= track.lyrics %></textarea>
<br><br>
  <input type="submit">
</form>

app/views/tracks/_track.html.erb
<li>
  <%= link_to track.title, track_url(track) %>
</li>

app/views/tracks/edit.html.erb
<h1> Edit '<%=@track.title %>'</h1>

<%= render "form", track: @track, current_album: @track.album%>



<%= button_to "Cancel", track_url(@track), method: :get%>

app/views/tracks/new.html.erb
<h1> Add track to <%=@track.album %></h1>

<%= render "form", track: @track, current_album: @album %>



<%= button_to "Cancel", album_url(@album), method: :get%>

app/views/tracks/show.html.erb
<h1> <%= @track.title %> </h1>

<%= button_to "Edit Track", edit_track_url(@track), method: :get %>
<%= button_to "Delete Track", track_url(@track), method: :delete %>


<ul>
  <li> Album: <%= @track.album.title %> </li>
  <li> Track Type:  <%= @track.track_type %> </li>
  <li> Lyrics:
    <% ugly_lyrics(@track.lyrics).each do |line|  %>
      <br>
        <%= line %>
    <% end %>
  </li>
</ul>

<br><br>

<h3>Notes: </h3>
<%= render "notes/form", track: @track %>
<%= render "notes/note", track: @track %>

<br>

<%= link_to "Back to #{@track.album.title}", album_url(@track.album) %>