config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:create, :new, :show] do
    get :activate, on: :collection
  end
  resource :session, only: [:create, :new, :destroy]

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, except: [:index, :new] do
    resources :tracks, only: [:new]
  end

  resources :tracks, except: [:index, :new] do
    resources :notes, only: [:create]
  end

  resources :notes, only: [:destroy]

end

app/models/album.rb
class Album < ApplicationRecord
  ALBUM_TYPES = %w(studio live)

  validates :title, presence: true
  validates :band_id, presence: true
  validates :album_type, inclusion: ALBUM_TYPES

  belongs_to :band
  has_many :tracks, dependent: :destroy
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  before_action :ensure_logged_in


  def new
    @band = Band.find(params[:band_id])
    @album = Album.new
    render :new
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      redirect_to album_url(@album)
    else
      flash[:errors] = @album.errors.full_messages
      redirect_to new_band_album_url(@album.band)
    end
  end

  def edit
    @album = Album.find(params[:id])
    render :edit
  end

  def update
    @album = Album.find(params[:id])
    if @album.update_attributes(album_params)
      redirect_to album_url(@album)
    else
      flash[:errors] = @album.errors.full_messages
      redirect_to edit_album_url(@album)
    end
  end

  def show
    @album = Album.find(params[:id])
    render :show
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy
    redirect_to band_url(@album.band)
  end

  private

  def album_params
    params.require(:album).permit(:title, :band_id, :album_type)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_album.html.erb
<li>
  <%= link_to album.title, album_url(album) %>
</li>

app/views/albums/_form.html.erb
<% action = (album.persisted? ? :edit : :new) %>

<form action= "<%= action==:edit ? album_url(album) : albums_url %>" method="post">
  <% if action == :edit %>
    <input type="hidden" name="_method" value="PATCH">
  <% end %>
  <%= auth_token %>

  <label for="album_title">Album title: </label>
  <input  type="text" name="album[title]"
          placeholder="Album title"
          value = "<%= album.title %>" >

  <br>

  <label for="album_band_id">Recording Artist</label>
  <select name="album[band_id]">
    <% Band.all.each do |band| %>
      <option value="<%= band.id %>"
              <%= 'selected' if current_band.name == band.name %>><%= band.name %></option>
    <% end %>
  </select>

  <br>

  <label>Studio
    <input type="radio"
      name="album[album_type]"
      value = "studio"
      <%= "checked" if album.album_type == "studio" %>>
  </label>
  <label>Live
    <input type="radio"
      name="album[album_type]"
      value = "live"
      <%= "checked" if album.album_type == "live" %>>
  </label>

  <br>

  <input type="submit">
</form>

app/views/albums/edit.html.erb
<h1>Edit <%= @album.title %></h1>

<%= render 'form', album: @album, current_band: @album.band %>

<%= button_to "Cancel", album_url(@album), method: :get %>

app/views/albums/new.html.erb
<h1>Add Album!</h1>

<%= render "form", album: @album, current_band: @band %>

<%= button_to "Cancel", band_url(@band), method: :get %>

app/views/albums/show.html.erb
<h1><%= @album.title %></h1>

<%= button_to "Edit Album", edit_album_url(@album), method: :get %>
<%= button_to "Delete Album", album_url(@album), method: :delete %>

<br>

<h3>Album info:</h3>
<ul>
  <li>Recording Artist: <%= @album.band.name %></li>
  <li>Album Type: <%= @album.album_type %></li>
</ul>

<h3>Track list:</h3>
<ul>
  <% @album.tracks.each do |track| %>
  <%= render 'tracks/track', track: track %>
  <% end %>
</ul>

<%= button_to "Add track", new_album_track_url(@album), method: :get %>
<br><br>

<%= link_to "Back to #{@album.band.name}", band_url(@album.band) %>