config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:create, :new, :show] do
    get :activate, on: :collection
  end
  resource :session, only: [:create, :new, :destroy]

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, except: [:index, :new] do
    resources :tracks, only: [:new]
  end

  resources :tracks, except: [:index, :new] do
    resources :notes, only: [:create]
  end

  resources :notes, only: [:destroy]

end

app/models/band.rb
class Band < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :albums, dependent: :destroy
  has_many :tracks, through: :albums, source: :tracks
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :ensure_logged_in
  
  def index
    @bands = Band.all
    render :index
  end

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_url(@band)
    else
      flash[:errors] = @band.errors.full_messages
      redirect_to new_band_url
    end
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def update
    @band = Band.find(params[:id])
    if @band.update_attributes(band_params)
      redirect_to band_url(@band)
    else
      flash[:errors] = @band.errors.full_messages
      redirect_to edit_band_url(@band)
    end
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def destroy
    @band = Band.find(params[:id])
    @band.destroy
    redirect_to bands_url
  end

  private

  def band_params
    params.require(:band).permit(:name)
  end
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/views/bands/_band.html.erb
<li>
  <%= link_to band.name, band_url(band) %>
</li>

app/views/bands/_form.html.erb
<% action = (band.persisted? ? :edit : :new) %>

<form action= "<%= action==:edit ? band_url(band) : bands_url %>" method="post">
  <% if action == :edit %>
    <input type="hidden" name="_method" value="PATCH">
  <% end %>
  <%= auth_token %>

  <label for="band_name">Band name: </label>
  <input  type="text" name="band[name]"
          placeholder="Band name"
          value = "<%= band.name %>" >

  <input type="submit">
</form>

app/views/bands/edit.html.erb
<h1>Edit <%= @band.name %></h1>

<%= render 'form', band: @band %>

app/views/bands/index.html.erb
<h1>Inventory</h1>

<ul>
  <%= render @bands %>
</ul>

<%= button_to "Add Band", new_band_url, method: :get %>

app/views/bands/new.html.erb
<h1>Add Band</h1>

<%= render "form", band: @band %>

app/views/bands/show.html.erb
<h1><%= @band.name %></h1>
<%= button_to "Edit band", edit_band_url(@band), method: :get %>
<%= button_to "Delete band", band_url(@band), method: :delete %>
<br>

<h3>Albums</h3>
<ul>
  <% @band.albums.each do |album| %>
  <%= render 'albums/album', album: album %>
  <% end %>
</ul>

<%= button_to "Add album", new_band_album_url(@band), method: :get %>

<br>
<br>

<%= link_to "Back to bands", bands_url %>